export const job_detail = {
  status: "OK",
  request_id: "dfb39fa3-ce96-4eb6-a60a-e448791f51f2",
  parameters: {
    query: "python developer in texas, usa",
    page: 1,
    num_pages: 1,
  },
  data: [
    {
      job_id: "p1-jGSG68qVtxL-QAAAAAA==",
      employer_name: "Verdant Infotech Solutions",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnJ6hHVsNfNYSHOGP2hFaf-k9G50C4ovK6T2Av&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-at-verdant-infotech-solutions-3896696381",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6431,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-at-verdant-infotech-solutions-3896696381",
          is_direct: false,
        },
        {
          publisher: "Dive Into Python",
          apply_link: "https://diveintopython.org/jobs/python-developer-8406",
          is_direct: false,
        },
        {
          publisher: "Monster",
          apply_link:
            "https://www.monster.com/job-openings/python-developer-copper-canyon-tx--e551bd20-84b9-45c8-8307-17d7b90203bb",
          is_direct: false,
        },
        {
          publisher: "Adzuna",
          apply_link: "https://www.adzuna.com/details/4621799872",
          is_direct: false,
        },
        {
          publisher: "Resume-Library.com",
          apply_link:
            "https://www.resume-library.com/feed/click/551/148413873?dpj=yes",
          is_direct: true,
        },
        {
          publisher: "Channel People",
          apply_link:
            "https://www.channelpeople-us.com/job/6rlpx8t2/python-developer",
          is_direct: false,
        },
      ],
      job_description:
        "Onsite in Plano, Texas from Day 1 for 3 times a week.\n\n6m+\n\nGC,USC\n\nVideo Interview\n\nNeeds\n\nPython\n\nApi's Ansible\n\nApp Dev profiles\n\nProject\n\nClient is building a brand new data center.\n\nThis team falls under the Devops umbrella, however there is no devops needed.\n\nThe Python app developer will be doing new development and automation of on prem processes.\n\nLooking for strong object orientation and class based programming\n\n|\n\n,\n\n5208 Windsor Ln, Copper Canyon, Texas, 75077",
      job_is_remote: false,
      job_posted_at_timestamp: 1712945254,
      job_posted_at_datetime_utc: "2024-04-12T18:07:34.000Z",
      job_city: "Copper Canyon",
      job_state: "TX",
      job_country: "US",
      job_latitude: 33.095955,
      job_longitude: -97.09668,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=p1-jGSG68qVtxL-QAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-05-12T17:52:32.000Z",
      job_offer_expiration_timestamp: 1715536352,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: false,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Python",
          "Looking for strong object orientation and class based programming",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      job_id: "jOCI5XgDPQloqgLyAAAAAA==",
      employer_name: "Wise Skulls",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYqsrQ2ibAYR71EZHt34pbrd4ySfLkDryEbNXs&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-at-wise-skulls-3888451316",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6423,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-at-wise-skulls-3888451316",
          is_direct: false,
        },
      ],
      job_description:
        "Title:Python Developer\n\nLocation: Dallas TX (Remote till Mid of January)\n\nDuration: 6+ Months (Possibility of Extension)\n\nImplementation Partner: Infosys\n\nEnd Client: To be Disclosed\n\nJD\n\nMinimum years of experience 6+ Years\n\nStrong Hands-on experience in SQL , Python and Teradata.",
      job_is_remote: false,
      job_posted_at_timestamp: 1712657566,
      job_posted_at_datetime_utc: "2024-04-09T10:12:46.000Z",
      job_city: "Dallas",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.776665,
      job_longitude: -96.79699,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=jOCI5XgDPQloqgLyAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-05-09T10:12:40.000Z",
      job_offer_expiration_timestamp: 1715249560,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 72,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Minimum years of experience 6+ Years",
          "Strong Hands-on experience in SQL , Python and Teradata",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      job_id: "Fu45CjGHb5nEAsiXAAAAAA==",
      employer_name: "Hewlett Packard Enterprise",
      employer_logo:
        "https://upload.wikimedia.org/wikipedia/commons/4/46/Hewlett_Packard_Enterprise_logo.svg",
      employer_website: "http://www.hpe.com",
      employer_company_type: "Information",
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-at-hewlett-packard-enterprise-3887109207",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6313,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-at-hewlett-packard-enterprise-3887109207",
          is_direct: false,
        },
        {
          publisher: "Jooble",
          apply_link: "https://jooble.org/jdp/-580738338802438457",
          is_direct: false,
        },
        {
          publisher: "Salary.com",
          apply_link:
            "https://www.salary.com/job/photon-interactive-uk-limited/python-developer/j202404100439182681121",
          is_direct: false,
        },
        {
          publisher: "LazyApply",
          apply_link: "https://lazyapply.com/jobpreview/job_0aeabf8a93dfbd4c",
          is_direct: false,
        },
      ],
      job_description:
        "Greetings from Photon, we are looking for a Python Developer with some Java experience Developer for one of our critical projects in Dallas, TX. Please have a look at the JD and share your resume with me at amit.chauhan@photon.com.\n\nRole : Python Developer (Only FTE/W2)\n\nLocation : Dallas, TX\n\nPython Developer Responsibilities:\n• Coordinating with development teams to determine application requirements.\n• Writing scalable code using Python programming language.\n• Testing and debugging applications.\n• Developing back-end components.\n• Integrating user-facing elements using server-side logic.\n• Assessing and prioritizing client feature requests.\n• Integrating data storage solutions.\n• Coordinating with front-end developers.\n• Reprogramming existing databases to improve functionality.\n• Developing digital tools to monitor online traffic.\n\nRequirements:\n• Bachelor's degree in computer science, computer engineering, or related field.\n• 7+ years of experience as a Python developer.\n• Knowledge of middleware Java stack, messaging technologies, containerization, web containers and test automation.\n• Expert knowledge of Python and related frameworks including Django and Flask.\n• A deep understanding and multi-process architecture and the threading limitations of Python.\n• Familiarity with server-side templating languages including Jinja 2 and Mako.\n• Ability to integrate multiple data sources into a single system.\n• Ability to collaborate on projects and work independently when required.\n• Expert-level development skills in Python\n• Expertise in different database technologies like Snowflake & NoSQL databases like MongoDB, DynamoDB\n• Demonstrated Experience coding in more than one programming language. Our full stack engineers work across a range of client, middle tier, messaging, caching and database technologies including Java, Python, TypeScript, JavaScript, SQL and PL/SQL\n• Experience with quant research processes, methodologies, and tools a plus.\n• Experience with Financial Datasets a plus.",
      job_is_remote: false,
      job_posted_at_timestamp: 1712670863,
      job_posted_at_datetime_utc: "2024-04-09T13:54:23.000Z",
      job_city: "Dallas",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.776665,
      job_longitude: -96.79699,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=Fu45CjGHb5nEAsiXAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-05-09T13:54:23.000Z",
      job_offer_expiration_timestamp: 1715262863,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 84,
        experience_mentioned: true,
        experience_preferred: true,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Bachelor's degree in computer science, computer engineering, or related field",
          "7+ years of experience as a Python developer",
          "Knowledge of middleware Java stack, messaging technologies, containerization, web containers and test automation",
          "Expert knowledge of Python and related frameworks including Django and Flask",
          "A deep understanding and multi-process architecture and the threading limitations of Python",
          "Familiarity with server-side templating languages including Jinja 2 and Mako",
          "Ability to integrate multiple data sources into a single system",
          "Ability to collaborate on projects and work independently when required",
          "Expert-level development skills in Python",
          "Expertise in different database technologies like Snowflake & NoSQL databases like MongoDB, DynamoDB",
          "Demonstrated Experience coding in more than one programming language",
          "Our full stack engineers work across a range of client, middle tier, messaging, caching and database technologies including Java, Python, TypeScript, JavaScript, SQL and PL/SQL",
        ],
        Responsibilities: [
          "Coordinating with development teams to determine application requirements",
          "Writing scalable code using Python programming language",
          "Testing and debugging applications",
          "Developing back-end components",
          "Integrating user-facing elements using server-side logic",
          "Assessing and prioritizing client feature requests",
          "Integrating data storage solutions",
          "Coordinating with front-end developers",
          "Reprogramming existing databases to improve functionality",
          "Developing digital tools to monitor online traffic",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
      job_naics_code: "511210",
      job_naics_name: "Software Publishers",
    },
    {
      job_id: "plFe20yLmAsjQut5AAAAAA==",
      employer_name: "TekIntegral",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGxr9R3VRG_gGLmxKHcxU1AqHviBwLr-cYBuz7&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Python developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-at-tekintegral-3888458773",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6347,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-at-tekintegral-3888458773",
          is_direct: false,
        },
      ],
      job_description:
        "Title: Python Developer\n\nLocation: Dallas Fort Worth, TX- will be more hybrid.\n\nLength: long-term - open-ended contract!\n\n5-6 yrs will work\n• This is a Python Automation Engineer/Python Developer type role - looking for automation skills with writing test scripts. Need to have robot framework, selenium, Wireshark and call flow exp. Any experience withing with 4G/5G, LET/VoLTE telecom domains.\n\nThe automation engineer at Telecommunication will work within a service development and maintenance engineering team responsible for writing scripts to test mobile voice and video services. Will be responsible for building and maintaining a library of automated tests to execute against the Telecommunication network, based on test plans provided by senior engineers. We are driving towards a zero-touch test environment.\n\nThe Position Requires\n\nMinimum of a BS degree in an engineering discipline is REQUIRED.\n\nMinimum of 2-4 years of overall programming experience is REQUIRED.\n\nMinimum of 2-4 years of overall testing experience is REQUIRED, PREFERRABLY in an automation environment.\n\nAt least 2 years of python programing experience in an automation environment is PREFERRED. Alternative languages include Perl, Groovy, Scala & JavaScript.\n\nSound understanding of programming and software concepts and principles including database, networking, json/xml, object oriented design is REQUIRED.\n\nAt least 2 years' experience of hands-on coding/scripting experience using Appium, Selenium, or a related mobile application automation framework (i.e. Perfecto Mobile) to test Android and iOS mobile applications is PREFERRED.\n\nFamiliarity with Testing Techniques and Methodologies - understanding of the various approaches used in testing, including white box (logic driven), black box (requirements driven), load testing, coverage testing and regression testing is REQUIRED.\n\nStrong Communication Skills (both Oral And Verbal) Are REQUIRED.\n\nAt least 1 year of Linux experience is REQUIRED.\n\nExperience with the Robot Framework for automated acceptance testing is DESIRED.\n\nKnowledge of and experience with IMS, SIP, VoIP and Video applications in a carrier/service provider/ISP environment is DESIRED.\n\nWorking knowledge of protocols, network technologies and standards including: 3GPP IMS-architecture, LTE, TCP/UDP, SIP, RTP, DNS, ENUM, GSMA-RCS, MMTel and other SIP/VoIP standards is DESIRED.\n\nExperience with debugging tools such as Wireshark and QXDM is DESIRED.\n\nKnowledge of other VoIP test, monitoring and debugging tools is DESIRED.\n\nPlease share resume at Career@tekintegral.com OR nkumar@tekintegral.com",
      job_is_remote: false,
      job_posted_at_timestamp: 1712657673,
      job_posted_at_datetime_utc: "2024-04-09T10:14:33.000Z",
      job_city: "Fort Worth",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.75549,
      job_longitude: -97.330765,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=plFe20yLmAsjQut5AAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-05-09T10:13:44.000Z",
      job_offer_expiration_timestamp: 1715249624,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 24,
        experience_mentioned: true,
        experience_preferred: true,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "5-6 yrs will work",
          "This is a Python Automation Engineer/Python Developer type role - looking for automation skills with writing test scripts",
          "Minimum of a BS degree in an engineering discipline is REQUIRED",
          "Minimum of 2-4 years of overall testing experience is REQUIRED, PREFERRABLY in an automation environment",
          "Alternative languages include Perl, Groovy, Scala & JavaScript",
          "Sound understanding of programming and software concepts and principles including database, networking, json/xml, object oriented design is REQUIRED",
          "At least 2 years' experience of hands-on coding/scripting experience using Appium, Selenium, or a related mobile application automation framework (i.e",
          "Familiarity with Testing Techniques and Methodologies - understanding of the various approaches used in testing, including white box (logic driven), black box (requirements driven), load testing, coverage testing and regression testing is REQUIRED",
          "Strong Communication Skills (both Oral And Verbal) Are REQUIRED",
          "At least 1 year of Linux experience is REQUIRED",
          "Experience with debugging tools such as Wireshark and QXD",
        ],
        Responsibilities: [
          "The automation engineer at Telecommunication will work within a service development and maintenance engineering team responsible for writing scripts to test mobile voice and video services",
          "Will be responsible for building and maintaining a library of automated tests to execute against the Telecommunication network, based on test plans provided by senior engineers",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      job_id: "2h2bsLlQZnIbGVTaAAAAAA==",
      employer_name: "PRICE WATERHOUSE COOPERS",
      employer_logo:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/PricewaterhouseCoopers_Logo.svg/1200px-PricewaterhouseCoopers_Logo.svg.png",
      employer_website: "http://www.pwc.com",
      employer_company_type: "Consulting",
      job_publisher: "Indeed",
      job_employment_type: "FULLTIME",
      job_title: "US Tech - Python Developer",
      job_apply_link: "https://www.indeed.com/viewjob?jk=045c37e3ee96b115",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6225,
      apply_options: [
        {
          publisher: "Indeed",
          apply_link: "https://www.indeed.com/viewjob?jk=045c37e3ee96b115",
          is_direct: false,
        },
        {
          publisher: "ZipRecruiter",
          apply_link:
            "https://www.ziprecruiter.com/c/PwC/Job/US-Tech-Python-Developer/-in-Dallas,TX?jid=6ee782286f0cb96c",
          is_direct: false,
        },
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/us-tech-python-developer-at-pwc-3890873982",
          is_direct: false,
        },
        {
          publisher: "SimplyHired",
          apply_link:
            "https://www.simplyhired.com/job/3vDreifcHoK8VrxHEGyHj6IXpBZU2uoUU3lo4MyLD1H3LWjt2j7MXQ",
          is_direct: false,
        },
        {
          publisher: "Talentify",
          apply_link:
            "https://www.talentify.io/job/us-tech-python-developer-dallas-texas-pwc-524561wd",
          is_direct: false,
        },
        {
          publisher: "Nexxt",
          apply_link:
            "https://www.nexxt.com/jobs/us-tech-python-developer-dallas-tx-2681321900-job.html?aff=2ED44C72-8FD2-4B5D-BC54-2F623E88BE26",
          is_direct: false,
        },
        {
          publisher: "Lensa",
          apply_link:
            "https://lensa.com/job/pwc/dallas-tx/python-developer/0b2891e483dcba556aa0beddadb9daa6",
          is_direct: false,
        },
        {
          publisher: "Jobilize",
          apply_link:
            "https://www.jobilize.com/job/us-tx-dallas-tech-python-developer-pwc-hiring-now-job-immediately",
          is_direct: false,
        },
      ],
      job_description:
        "A career in Products and Technology is an opportunity to bring PwC's strategy to life by driving products and technology into everything we deliver. Our clients expect us to bring the right people and the right technology to solve their biggest problems; Products and Technology is here to help PwC meet that challenge and accelerate the growth of our business. We have skilled technologists, data scientists, product managers and business strategists who are using technology to accelerate change. Our team is responsible for all software engineering activities to ensure that business objectives are met. This includes the creation, development, design, and improvement of products, software, applications, and services. These roles are responsible for the development of computer programming systems and applications including the design, coding, testing and deployment of products and solutions to meet business obligations.\n\nTo really stand out and make us fit for the future in a constantly changing world, each and every one of us at PwC needs to be an authentic and inclusive leader, at all grades/levels and in all lines of service. To help us achieve this we have the PwC Professional; our global leadership development framework. It gives us a single set of expectations across our lines, geographies and career paths, and provides transparency on the skills we need as individuals to be successful and progress in our careers, now and in the future.\n\nAs a Manager, you'll work as part of a team of problem solvers, helping to solve complex business issues from strategy to execution. PwC Professional skills and responsibilities for this management level include but are not limited to:\n• Pursue opportunities to develop existing and new skills outside of comfort zone.\n• Act to resolve issues which prevent effective team working, even during times of change and uncertainty.\n• Coach others and encourage them to take ownership of their development.\n• Analyse complex ideas or proposals and build a range of meaningful recommendations.\n• Use multiple sources of information including broader stakeholder views to develop solutions and recommendations.\n• Address sub-standard work or work that does not meet firm's/client's expectations.\n• Develop a perspective on key global trends, including globalisation, and how they impact the firm and our clients.\n• Manage a variety of viewpoints to build consensus and create positive outcomes for all parties.\n• Focus on building trusted relationships.\n• Uphold the firm's code of ethics and business conduct.\n\nJob Requirements and Preferences:\n\nBasic Qualifications:\n\nMinimum Degree Required:\nBachelor Degree\n\nMinimum Years of Experience:\n4 year(s) of experience in progressive roles focused in data analytics, development and data architecture.\n\nPreferred Qualifications:\n\nPreferred Knowledge/Skills:\n\nDemonstrates extensive knowledge and/or a proven record of success in applied subject matter such as IT, finance, accounting, energy or health care role emphasizing data modeling and analytics for a global network of professional services firms, including the following areas:\n• Understanding of database storage models including NoSQL (Graph, MongoDB, etc) database models, XML, relational and other database models and associated SQL;\n• Understanding of ETL tools and techniques, such as tools like Talent, Mapforce, how to map transformation and flow of data from a source to a target system;\n• Performing in development language environments e.g. C#, Python, Java, or equivalent and applying analytical methods to large and complex datasets leveraging one of those languages;\n• Automating complex processes;\n• Translating business requirements into relevant data models; and,\n• Utilizing and applying into projects knowledge of technologies such as machine learning frameworks provided by Microsoft, Google, Amazon, etc.\n\nDemonstrates extensive abilities and/or a proven record of success in the application of technical requirements translation, data modeling, data mining or data-driven problem solving, including the following areas:\n• Understanding of database storage models including NoSQL (Graph, MongoDB, etc) database models, XML, relational and other database models and associated SQL;\n• Understanding of ETL tools and techniques, such as tools like Talent, Mapforce, how to map transformation and flow of data from a source to a target system;\n• Demonstrating proficiency in developing batch and streaming application using Python;\n• Demonstrating experience in using Spark or Azure Databricks Platform, Databricks Delta Lake;\n• Utilizing programming skills and knowledge on how to write models which can be directly used in production as part of a large scale system;\n• Utilizing and applying into projects knowledge of data wrangling techniques and scripting languages with proven ability in working on a cloud based infrastructure environment;\n• Understanding how to develop data analytic models and operationalize these models so they can run in an automated context;\n• Working independently with minimal guidance;\n• Leveraging problem solving and troubleshooting skills with proven ability exercising mature judgment;\n• Prioritizing effectively workload to meet deadlines and work objectives;\n• Writing clearly and succinctly in a manner that appeals to a wide audience;\n• Communicating complex engineering concepts succinctly to senior non-technical and technical decision makers;\n• Performing development, data analytics and programming/scripting, especially C#, Java, Scala, C++, R, SQL, etc.;\n• Visualizing and communicating analytical results, ideally using open source visualization technologies such as HTML, JavaScript, and related packages such as D3, Tableau, and PowerBI;\n• Using large data sets, along with analytical scripting tools and visualization platforms to produce actionable insights for clients, data cleansing, transformation, and modeling in order to produce a clear story that is easily comprehended by non-technical audiences;\n• Leading, training and working with others in designing effective analytical approaches taking into consideration performance and scalability to large datasets; and,\n• Performing unit and system testing to validate the output of the analytic procedures against expected results.\n\nLearn more about how we work: https://pwc.to/how-we-work\n\nPwC does not intend to hire experienced or entry level job seekers who will need, now or in the future, PwC sponsorship through the H-1B lottery, except as set forth within the following policy: https://pwc.to/H-1B-Lottery-Policy.\n\nAll qualified applicants will receive consideration for employment at PwC without regard to race; creed; color; religion; national origin; sex; age; disability; sexual orientation; gender identity or expression; genetic predisposition or carrier status; veteran, marital, or citizenship status; or any other status protected by law. PwC is proud to be an affirmative action and equal opportunity employer.\n\nFor positions in California, Colorado, Hawaii, Nevada, New York State, or Washington State, or for opportunities that will report to a supervisor, office or other work site in New York State, please visit the following link for pay range information: https://pwc.to/payrange-v1-productstechmanager",
      job_is_remote: false,
      job_posted_at_timestamp: 1712838824,
      job_posted_at_datetime_utc: "2024-04-11T12:33:44.000Z",
      job_city: "Dallas",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.776665,
      job_longitude: -96.79699,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=2h2bsLlQZnIbGVTaAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-08-11T14:59:08.000Z",
      job_offer_expiration_timestamp: 1723388348,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: true,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "4 year(s) of experience in progressive roles focused in data analytics, development and data architecture",
          "Demonstrates extensive knowledge and/or a proven record of success in applied subject matter such as IT, finance, accounting, energy or health care role emphasizing data modeling and analytics for a global network of professional services firms, including the following areas:",
          "Demonstrates extensive abilities and/or a proven record of success in the application of technical requirements translation, data modeling, data mining or data-driven problem solving, including the following areas:",
          "Demonstrating experience in using Spark or Azure Databricks Platform, Databricks Delta Lake;",
          "Utilizing and applying into projects knowledge of data wrangling techniques and scripting languages with proven ability in working on a cloud based infrastructure environment;",
          "Leveraging problem solving and troubleshooting skills with proven ability exercising mature judgment;",
          "Performing development, data analytics and programming/scripting, especially C#, Java, Scala, C++, R, SQL, etc.;",
        ],
        Responsibilities: [
          "This includes the creation, development, design, and improvement of products, software, applications, and services",
          "These roles are responsible for the development of computer programming systems and applications including the design, coding, testing and deployment of products and solutions to meet business obligations",
          "As a Manager, you'll work as part of a team of problem solvers, helping to solve complex business issues from strategy to execution",
          "Pursue opportunities to develop existing and new skills outside of comfort zone",
          "Act to resolve issues which prevent effective team working, even during times of change and uncertainty",
          "Coach others and encourage them to take ownership of their development",
          "Analyse complex ideas or proposals and build a range of meaningful recommendations",
          "Use multiple sources of information including broader stakeholder views to develop solutions and recommendations",
          "Address sub-standard work or work that does not meet firm's/client's expectations",
          "Develop a perspective on key global trends, including globalisation, and how they impact the firm and our clients",
          "Manage a variety of viewpoints to build consensus and create positive outcomes for all parties",
          "Focus on building trusted relationships",
          "Uphold the firm's code of ethics and business conduct",
          "Performing in development language environments e.g. C#, Python, Java, or equivalent and applying analytical methods to large and complex datasets leveraging one of those languages;",
          "Automating complex processes;",
          "Translating business requirements into relevant data models; and,",
          "Utilizing and applying into projects knowledge of technologies such as machine learning frameworks provided by Microsoft, Google, Amazon, etc",
          "Understanding how to develop data analytic models and operationalize these models so they can run in an automated context;",
          "Working independently with minimal guidance;",
          "Prioritizing effectively workload to meet deadlines and work objectives;",
          "Writing clearly and succinctly in a manner that appeals to a wide audience;",
          "Using large data sets, along with analytical scripting tools and visualization platforms to produce actionable insights for clients, data cleansing, transformation, and modeling in order to produce a clear story that is easily comprehended by non-technical audiences;",
          "Leading, training and working with others in designing effective analytical approaches taking into consideration performance and scalability to large datasets; and,",
          "Performing unit and system testing to validate the output of the analytic procedures against expected results",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
      job_naics_code: "541613",
      job_naics_name: "Marketing Consulting Services",
    },
    {
      job_id: "WOrGbZY3up5vpeRyAAAAAA==",
      employer_name: "SmartIPlace",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmbIAqElxdvwLigWST7QwLEJhiaHPCGZF4ecHR&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer with GIS Experience",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-with-gis-experience-at-smartiplace-3895663258",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6357,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-with-gis-experience-at-smartiplace-3895663258",
          is_direct: false,
        },
        {
          publisher: "ZipRecruiter",
          apply_link:
            "https://www.ziprecruiter.com/c/SmartIPlace/Job/Python-Developer-with-GIS-Experience/-in-Irving,TX?jid=a0fed6c4fcc770a9",
          is_direct: true,
        },
        {
          publisher: "Monster",
          apply_link:
            "https://www.monster.com/job-openings/python-developer-with-gis-experience-irving-tx--ad62864a-e7cd-4c2e-a108-9ae9a52bb024",
          is_direct: true,
        },
        {
          publisher: "Interlink Jobs",
          apply_link: "https://www.interlinkjobs.com/jobs/57582399/apply",
          is_direct: false,
        },
      ],
      job_description:
        "Title- Python Developer With GIS Experience\n\nLocation- Irving, TX (Hybrid 3 Days a week) Local only\n\nVisa- USC/GC/GC-EAD/H4-EAD\n• supporting state specific, county specific ideas. Understand assisting tools and take new request, develop, and design. Team works in Python. Design the process. Need to understand how to build the task list and get the work done.\n• MUST have python- be able to write based on requirements. Can take requirements and develop a project out of it.\n• MUST be able to understand and describe data types, model solutions end to end.\n• Title: more Python Developer on this one, more processing of things. Doing work on web API back-end, doing stuff on a fiber route analysis. Does need familiarity of data but more python developer.\n• A lot is address related data, need to be good with data. Converting business requirements to a data pipeline is what they are looking for.\n• MUST have:\n• Base understanding of data and data types. Something from excel, raw value, it has comas and it needs to be cleaned up first. Understanding of data types and proper usage in it.\n• Flexible in solutions\n• Postgres is main – but doesn’t need to be locked into 1 database type\n• Location: Irving at hub, 3 days onsite – non negotiable\n• IV process: 1 technical, then a non formal meeting w/ team\n• On Python one, does a take home test",
      job_is_remote: false,
      job_posted_at_timestamp: 1712950782,
      job_posted_at_datetime_utc: "2024-04-12T19:39:42.000Z",
      job_city: "Irving",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.81402,
      job_longitude: -96.94889,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=WOrGbZY3up5vpeRyAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-10-09T19:39:43.000Z",
      job_offer_expiration_timestamp: 1728502783,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Can take requirements and develop a project out of it",
          "Does need familiarity of data but more python developer",
          "A lot is address related data, need to be good with data",
          "Converting business requirements to a data pipeline is what they are looking for",
          "Base understanding of data and data types",
          "Something from excel, raw value, it has comas and it needs to be cleaned up first",
        ],
        Responsibilities: [
          "Understand assisting tools and take new request, develop, and design",
          "Team works in Python",
          "Need to understand how to build the task list and get the work done",
          "MUST be able to understand and describe data types, model solutions end to end",
          "Title: more Python Developer on this one, more processing of things",
          "Doing work on web API back-end, doing stuff on a fiber route analysis",
        ],
      },
      job_job_title: "Experience",
      job_posting_language: "en",
      job_onet_soc: "19309200",
      job_onet_job_zone: "5",
    },
    {
      job_id: "e8E_iTAk4UR8DwhKAAAAAA==",
      employer_name: "Extend Information Systems Inc.",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpOSK255X2-kDEDQwIAhqbXdSrPX_29Xs4WaYT&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer Irving, TX Full-time",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-irving-tx-full-time-at-extend-information-systems-inc-3888447175",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6427,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-irving-tx-full-time-at-extend-information-systems-inc-3888447175",
          is_direct: false,
        },
      ],
      job_description:
        "Hi Jobseeker ,\n\nI hope you are doing well!\n\nWe have an opportunity for Python Developer with one of our clients for Irving, TX (Day 1 onsite)\n\nPlease see the job details below and let me know if you would be interested in this role.\n\nIf interested, please send me a copy of your resume, contact details, availability, and a good time to connect with you.\n\nTitle Python Developer\n\nLocation: Irving, TX (Day 1 onsite)\n\nTerms: Fulltime\n\nJob Details\n\nTechnical/Functional Skills\n• Advanced Python knowledge with minimum 4-5 years relevant experience.\n• Knowledge on REST API using python Flask, integration with Mongodb.\n• Basic knowledge on unix commands.\n\nPriyanka tiwari\n\nExtend Information System Inc\n\nPhone: (703) 956-1120\n\nEmail: priyanka1@extendinfosys.com\n\n44258 Mercure Circle, UNIT 102 A, Sterling VA, USA 20166",
      job_is_remote: false,
      job_posted_at_timestamp: 1712657514,
      job_posted_at_datetime_utc: "2024-04-09T10:11:54.000Z",
      job_city: "Irving",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.81402,
      job_longitude: -96.94889,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=e8E_iTAk4UR8DwhKAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-05-09T10:11:51.000Z",
      job_offer_expiration_timestamp: 1715249511,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 48,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Advanced Python knowledge with minimum 4-5 years relevant experience",
          "Knowledge on REST API using python Flask, integration with Mongodb",
          "Basic knowledge on unix commands",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      job_id: "cROR1bcvrynF59wWAAAAAA==",
      employer_name: "Dice",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
      employer_website: null,
      employer_company_type: "Information",
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-at-dice-3888305317",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6276,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-at-dice-3888305317",
          is_direct: false,
        },
        {
          publisher: "Ladders",
          apply_link:
            "https://www.theladders.com/job-listing/python-developer-klimbnow-llc-houston-tx-_v2_-7-3646000040.html",
          is_direct: false,
        },
        {
          publisher: "Salary.com",
          apply_link:
            "https://www.salary.com/job/klimbnow-llc/python-developer/j202403110342085748572",
          is_direct: false,
        },
        {
          publisher: "Python Jobs",
          apply_link:
            "https://pythonjob.xyz/job/2ejuGhkyljHFYuEJlejNY6Egf9w/Python%20Developer",
          is_direct: false,
        },
        {
          publisher: "Houston, TX - Geebo",
          apply_link:
            "https://houston-tx.geebo.com/jobs-online/view/id/1355281032-python-developer-/",
          is_direct: false,
        },
        {
          publisher: "Jobilize",
          apply_link:
            "https://www.jobilize.com/job/us-tx-houston-python-developer-innova-solutions-hiring-now-job-immediately",
          is_direct: false,
        },
        {
          publisher: "Rhoobi.com",
          apply_link:
            "https://www.rhoobi.com/software/TX/Houston/Klimbnow%2C-LLC/Python-developer/29910949202",
          is_direct: false,
        },
      ],
      job_description:
        "Dice is the leading career destination for tech experts at every stage of their careers. Our client, Innova Solutions, Inc, is seeking the following. Apply via Dice today!\n\nPosition type: Full-time -- Contract Location: Hybrid Houston, TX No Corp to Corp. W2 contractors only please.\n\nAs a Python Developer, you will:\n\nDevelopment and support therein of the Openlink Endur trade capture and risk management system. This is the system of record for the global commodities desk. The job includes development of processes and reports using the proprietary AVS and JVS languages that enable trade booking to enable the desk to trade existing and new products, risk management and PL reporting to manage exposures, invoicing and confirmations to effectively manage back-office activities. Python knowledge is an ideal skillset.\n\nOpenlink Experience\n\nPython\n\nExperience with Financial Domains\n\nQualified candidates should APPLY NOW for immediate consideration! Please hit APPLY to provide the required information, and we will be back in touch as soon as possible.\n\nWe are currently interviewing to fill this and other similar positions. If this role is not a fit for you, we do offer a referral bonus program for referrals that we successfully place with our clients, subject to program guidelines. ASK ME HOW.\n\nPAY RANGE AND BENEFITS: Pay Range*: $65- $68per hour on W2\n• Pay range offered to a successful candidate will be based on several factors, including the candidate's education, work experience, work location, specific job duties, certifications, etc.\n\nBenefits: Innova Solutions offers benefits(based on eligibility) that include the following: Medical & pharmacy coverage, Dental/vision insurance, 401(k), Health saving account (HSA) and Flexible spending account (FSA), Life Insurance, Pet Insurance, Short term and Long term Disability, Accident & Critical illness coverage, Pre-paid legal & ID theft protection, Sick time, and other types of paid leaves (as required by law), Employee Assistance Program (EAP).\n\nABOUT INNOVA SOLUTIONS: Founded in 1998 and headquartered in Atlanta, Georgia, Innova Solutions employs approximately 50,000 professionals worldwide and reports an annual revenue approaching $3 Billion. Through our global delivery centers across North America, Asia, and Europe, we deliver strategic technology and business transformation solutions to our clients, enabling them to operate as leaders within their fields.\n\nRecent Recognitions:\n\nOne of Largest IT Consulting Staffing firms in the USA Recognized as #4 by Staffing Industry Analysts (SIA 2022)\n\nClearlyRated Client Diamond Award Winner (2020)\n\nOne of the Largest Certified MBE Companies in the NMSDC Network (2022)\n\nAdvanced Tier Services partner with AWS and Gold with MS\n\nInnova Solutions is an Equal Opportunity Employer and prohibits any kind of unlawful discrimination and harassment. Innova Solutions is committed to the principle of equal employment opportunity for all employees and to providing employees with a work environment free of discrimination and harassment on the basis of race, color, religion or belief, national origin, citizenship, social or ethnic origin, sex, age, physical or mental disability, veteran status, marital status, domestic partner status, sexual orientation, or any other status protected by the statutes, rules, and regulations in the locations where it operates. If you are an individual with a disability and need a reasonable accommodation to assist with your job search or application for employment, please contact us at or . Please indicate the specifics of the assistance needed. Innova Solutions encourages all interested and qualified candidates to apply for employment opportunities. Innova Solutions (HireGenics/Volt) does not discriminate against applicants based on citizenship status, immigration status, or national origin, in accordance with 8 U.S.C. 1324b.\n\nThe company will consider for employment qualified applicants with arrest and conviction records in a manner that complies with the San Francisco Fair Chance Ordinance, the Los Angeles Fair Chance Initiative for Hiring Ordinance, and other applicable laws.",
      job_is_remote: false,
      job_posted_at_timestamp: 1712612009,
      job_posted_at_datetime_utc: "2024-04-08T21:33:29.000Z",
      job_city: "Houston",
      job_state: "TX",
      job_country: "US",
      job_latitude: 29.760427,
      job_longitude: -95.369804,
      job_benefits: [
        "paid_time_off",
        "health_insurance",
        "dental_coverage",
        "retirement_savings",
      ],
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=cROR1bcvrynF59wWAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-05-08T21:33:29.000Z",
      job_offer_expiration_timestamp: 1715204009,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: true,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Python knowledge is an ideal skillset",
          "Openlink Experience",
        ],
        Responsibilities: [
          "Development and support therein of the Openlink Endur trade capture and risk management system",
          "The job includes development of processes and reports using the proprietary AVS and JVS languages that enable trade booking to enable the desk to trade existing and new products, risk management and PL reporting to manage exposures, invoicing and confirmations to effectively manage back-office activities",
        ],
        Benefits: [
          "PAY RANGE AND BENEFITS: Pay Range*: $65- $68per hour on W2",
          "Pay range offered to a successful candidate will be based on several factors, including the candidate's education, work experience, work location, specific job duties, certifications, etc",
          "Benefits: Innova Solutions offers benefits(based on eligibility) that include the following: Medical & pharmacy coverage, Dental/vision insurance, 401(k), Health saving account (HSA) and Flexible spending account (FSA), Life Insurance, Pet Insurance, Short term and Long term Disability, Accident & Critical illness coverage, Pre-paid legal & ID theft protection, Sick time, and other types of paid leaves (as required by law), Employee Assistance Program (EAP)",
          "ABOUT INNOVA SOLUTIONS: Founded in 1998 and headquartered in Atlanta, Georgia, Innova Solutions employs approximately 50,000 professionals worldwide and reports an annual revenue approaching $3 Billion",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
      job_naics_code: "519130",
      job_naics_name:
        "Internet Publishing and Broadcasting and Web Search Portals",
    },
    {
      job_id: "bDEFuu9YtP5ELRMeAAAAAA==",
      employer_name: "Ascendion",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4m_SUoefNn4uW7pQskaDTcGjjaV5ktFJDnnCF&s=0",
      employer_website: "http://www.ascendion.com",
      employer_company_type: null,
      job_publisher: "Indeed",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer",
      job_apply_link: "https://www.indeed.com/viewjob?jk=8763de7deaf75784",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6494,
      apply_options: [
        {
          publisher: "Indeed",
          apply_link: "https://www.indeed.com/viewjob?jk=8763de7deaf75784",
          is_direct: false,
        },
        {
          publisher: "Glassdoor",
          apply_link:
            "https://www.glassdoor.com/job-listing/python-developer-ascendion-JV_IC1140006_KO0,16_KE17,26.htm?jl=1009232590642",
          is_direct: false,
        },
        {
          publisher: "SimplyHired",
          apply_link:
            "https://www.simplyhired.com/job/pko0vAtlVOeAIrdi7LByAgxuCjnoYaipejHocD_3iwp6ihoPX_vRGg",
          is_direct: false,
        },
        {
          publisher: "LazyApply",
          apply_link: "https://lazyapply.com/jobpreview/job_8763de7deaf75784",
          is_direct: false,
        },
      ],
      job_description:
        "Description\n\nAbout Ascendion\n\nAscendion is a full-service digital engineering solutions company. We make and manage software platforms and products that power growth and deliver captivating experiences to consumers and employees. Our engineering, cloud, data, experience design, and talent solution capabilities accelerate transformation and impact for enterprise clients. Headquartered in New Jersey, our workforce of 6,000+ Ascenders delivers solutions from around the globe. Ascendion is built differently to engineer the next.\n\nAscendion | Engineering to elevate life\n\nWe have a culture built on opportunity, inclusion, and a spirit of partnership. Come, change the world with us:\n• Build the coolest tech for world’s leading brands\n• Solve complex problems – and learn new skills\n• Experience the power of transforming digital engineering for Fortune 500 clients\n• Master your craft with leading training programs and hands-on experience\n\nExperience a community of change makers!\n\nJoin a culture of high-performing innovators with endless ideas and a passion for tech. Our culture is the fabric of our company, and it is what makes us unique and diverse. The way we share ideas, learning, experiences, successes, and joy allows everyone to be their best at Ascendion\n\nAbout the Role:\n\nJob Title: UI Developer\n\nRequired:\n• 4-8 years hands-on development experience including writing and testing code, debugging programs and integrating applications with third-party web services.\n• AWS Serverless (Lambda + DynamoDB + S3 + SQS + SNS) PostgreSQL.\n• Write effective, scalable code.\n• Develop back-end components to improve responsiveness and overall performance.\n• Integrate user-facing elements into applications.\n• Test and debug programs\n• Improve functionality of existing systems\n• Implement security and data protection solutions.\n• Assess and prioritize feature requests\n• Strong expertise Python Full stack and Flask/Django development\n• Knowledge of object-relational mapping (ORM)\n• Familiarity with front-end technologies (like JavaScript and HTML5)\n• Effective collaboration with other cross-functional teams to ensure high-performance of applications.\n• Excellent communication and teamwork skills.\n\nLocation : Irving TX\n\nSalary Range: The salary for this position is between $90 – $105K annually. Factors which may affect pay within this range may include geography/market, skills, education, experience, and other qualifications of the successful candidate.\n\nBenefits: The Company offers the following benefits for this position, subject to applicable eligibility requirements: [medical insurance] [dental insurance] [vision insurance] [401(k) retirement plan] [long-term disability insurance] [short-term disability insurance] [5 personal days accrued each calendar year. The Paid time off benefits meet the paid sick and safe time laws that pertains to the City/ State] [10-15 days of paid vacation time] [6 paid holidays and 1 floating holiday per calendar year] [Ascendion Learning Management System]\n\nWant to change the world? Let us know.\n\nTell us about your experiences, education, and ambitions. Bring your knowledge, unique viewpoint, and creativity to the table. Let’s talk!\n\nPreferred Skills:\n• Python\n\npostgreSQL\n\nORM\n\nFlask\n\nDjango\n\nJob details\n\nJob ID\n\n329982\n\nJob Requirements\n\nPython Developer\n\nLocation\n\nIrving, Texas, US\n\nRecruiter\n\nRochit\n\nEmail\n\nrochit.mouriya@ascendion.com\n\n?>",
      job_is_remote: false,
      job_posted_at_timestamp: 1712865017,
      job_posted_at_datetime_utc: "2024-04-11T19:50:17.000Z",
      job_city: "Irving",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.81402,
      job_longitude: -96.94889,
      job_benefits: [
        "retirement_savings",
        "paid_time_off",
        "health_insurance",
        "dental_coverage",
      ],
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=bDEFuu9YtP5ELRMeAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-08-10T03:26:08.000Z",
      job_offer_expiration_timestamp: 1723260368,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 48,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: 90000,
      job_max_salary: 105000,
      job_salary_currency: "USD",
      job_salary_period: "YEAR",
      job_highlights: {
        Qualifications: [
          "4-8 years hands-on development experience including writing and testing code, debugging programs and integrating applications with third-party web services",
          "AWS Serverless (Lambda + DynamoDB + S3 + SQS + SNS) PostgreSQL",
          "Strong expertise Python Full stack and Flask/Django development",
          "Knowledge of object-relational mapping (ORM)",
          "Familiarity with front-end technologies (like JavaScript and HTML5)",
          "Effective collaboration with other cross-functional teams to ensure high-performance of applications",
          "Excellent communication and teamwork skills",
          "Bring your knowledge, unique viewpoint, and creativity to the table",
        ],
        Responsibilities: [
          "Build the coolest tech for world’s leading brands",
          "Solve complex problems – and learn new skills",
          "Experience the power of transforming digital engineering for Fortune 500 clients",
          "Master your craft with leading training programs and hands-on experience",
          "Write effective, scalable code",
          "Develop back-end components to improve responsiveness and overall performance",
          "Integrate user-facing elements into applications",
          "Improve functionality of existing systems",
          "Implement security and data protection solutions",
          "Assess and prioritize feature requests",
        ],
        Benefits: [
          "Salary Range: The salary for this position is between $90 – $105K annually",
          "Factors which may affect pay within this range may include geography/market, skills, education, experience, and other qualifications of the successful candidate",
          "Benefits: The Company offers the following benefits for this position, subject to applicable eligibility requirements: [medical insurance] [dental insurance] [vision insurance] [401(k) retirement plan] [long-term disability insurance] [short-term disability insurance] [5 personal days accrued each calendar year",
          "The Paid time off benefits meet the paid sick and safe time laws that pertains to the City/ State] [10-15 days of paid vacation time] [6 paid holidays and 1 floating holiday per calendar year] [Ascendion Learning Management System]",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      job_id: "457f-RJg7l3hzpXuAAAAAA==",
      employer_name: "Extend Information Systems Inc.",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpOSK255X2-kDEDQwIAhqbXdSrPX_29Xs4WaYT&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-at-extend-information-systems-inc-3888434925",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6427,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-at-extend-information-systems-inc-3888434925",
          is_direct: false,
        },
      ],
      job_description:
        "Hi,\n\nSourabh this side. We do have a new an excellent opportunity for you. This opportunity is a Fulltime position as Python Developer On-Site Please have a look at the job description below and let me know if you or someone you know is interested in this role. You can mail me At Sourabh@extendinfosys.com\n\nJob Title Python Developer\n\nLocation Houston, TX\n\nJob Type Full Time\n\nJd\n• 5+ years' experience as Python developer.\n• Hands on experience in Django framework.\n• Strong exposure and development experience using Time series data.\n• Regression models (simple and more advanced techniques, linear and non-linear),\n• Time series modelling\n• Standard array of statistical software packages (Python, R, EViews, SAS)\n• Azure fundamentals\n• Power BI foundation level knowledge\n\nThanks,\n\nSourabh | Technical Recruiter\n\nCell: 571-473-5044\n\nEmail: Sourabh@extendinfosys.com\n\nAddress: 44258 Mercure Circle, UNIT 102 A, Sterling VA, USA - 20166\n\nWeb: WWW.extendinfosys.com",
      job_is_remote: false,
      job_posted_at_timestamp: 1712657452,
      job_posted_at_datetime_utc: "2024-04-09T10:10:52.000Z",
      job_city: "Houston",
      job_state: "TX",
      job_country: "US",
      job_latitude: 29.760427,
      job_longitude: -95.369804,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=457f-RJg7l3hzpXuAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-05-09T10:10:48.000Z",
      job_offer_expiration_timestamp: 1715249448,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 60,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "5+ years' experience as Python developer",
          "Hands on experience in Django framework",
          "Strong exposure and development experience using Time series data",
          "Power BI foundation level knowledge",
        ],
        Benefits: [
          "Regression models (simple and more advanced techniques, linear and non-linear),",
          "Time series modelling",
          "Standard array of statistical software packages (Python, R, EViews, SAS)",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
  ],
};
